describe('Cadastro com email já cadastrado', () => {
  it('Não deve permitir cadastro com email já cadastrado', () => {
    cy.visit('https://paciente-staging.lacreisaude.com.br/saude/paciente/cadastrar/')
    cy.get('[name="firstName"]').click().type('Yuri')
    cy.get('[name="lastName"]').click().type('Tiango')
    cy.get('[name="email"]').click().type('yuritiangoh@gmail.com')
    cy.get('[name="email2"]').click().type('yuritiangoh@gmail.com')
    cy.get('[name="password1"]').click().type('Saude321@')
    cy.get('[name="password2"]').click().type('Saude321@')
    cy.get('[name="acceptedPrivacyDocument"]').click()
    cy.get('[name="is18YearsOldOrMore"]').click()
    cy.get('.cyCzPm > .sc-fThUAz').click()
    cy.contains('Já existe um usuário cadastrado com este endereço de e-mail.')
    .should('be.visible')
})
})